#define insteon devices
#insteon switches and buttons
0:
 address: '1C.56.67' 
 devtype: 'switchlinc'
 devname: 'lr light switch'

#insteon bulbs
1:
 address: '21.EE.7C'
 devtype: 'lightbulb'
 devname: 'master bedroom lamp'
 dimmable: '1'

#insteon applianclincs
2:
 address: '20.BC.93'
 devtype: 'appliancelinc'
 devname: 'lr lights'

#insteon motion sensors
3:
 address: '23.40.76'
 devtype: 'motionsensor'
 devname: 'front door sensor'

#insteon scene
#- scene_address:   ''
#scene_name:        ''
